# Generated by Django 5.2 on 2025-04-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('service_needed', models.CharField(choices=[('screen_replacement', 'Screen Replacement'), ('battery_replacement', 'Battery Replacement'), ('water_damage_repair', 'Water Damage Repair'), ('software_issue', 'Software Issue'), ('other', 'Other')], max_length=30)),
                ('preferred_date', models.DateField()),
                ('device_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUsEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('subject', models.CharField(choices=[('inquiry', 'General Inquiry'), ('feedback', 'Feedback/Suggestions'), ('technical_support', 'Technical Support'), ('repair_status', 'Repair Status'), ('business_inquiry', 'Business Inquiry'), ('other', 'Other')], max_length=30)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('item_image', models.URLField(blank=True, null=True)),
                ('item_brand', models.CharField(blank=True, choices=[('apple', 'Apple'), ('samsung', 'Samsung'), ('dell', 'Dell'), ('hp', 'HP'), ('lenovo', 'Lenovo'), ('xiomi', 'Xiomi'), ('microsoft', 'Microsoft')], max_length=20, null=True)),
                ('item_type', models.CharField(blank=True, choices=[('personal_computer', 'Personal Computer'), ('laptop', 'Laptop'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('watch', 'Watch'), ('headphones', 'Headphones'), ('accessory', 'Accessory')], max_length=20, null=True)),
                ('item_quantity', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
