# Generated by Django 5.2 on 2025-04-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AppointmentEmails',
            new_name='AppointmentEmail',
        ),
        migrations.RenameModel(
            old_name='ContactUsEmails',
            new_name='ContactUsEmail',
        ),
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
